name = ("Dito ")
surname = (" Samnidze ")
age = ( "14wlis ")
location = (" Tbilisi ")
occupation = (" Footballer and Programmer ")
hobby = (" Driving a car,making edits and Reading books ")
rank = (" School student ")
grade =(" 8th grade ")
good_trait = (" Kind and confidence ")
bad_trait = (" loves to eat too much but can't gain weight ")

print(name + surname + age + location + occupation + hobby + rank + grade + good_trait + bad_trait)